version: '3'

services:
  node-app:
    build: .
    links:
      - mongodb
    restart: always
    image: node-app
    environment:
      - MONGODB_URL_DOCKER=mongodb://mongodb:27017/barcode-api
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
